service: layer-section

provider:
  name: aws
  environment:
    NODE_PATH: "./:/opt/node_modules"

package:
  exclude:
    - octokit_layer/**

layers:
  octokit_Module:
    path: octokit_layer
    description: "Contains octokit and AWS SDK modules"
    
